//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSpectrumAnalyzerGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTLSpectrumAnalyzerGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the user analysis form.
        ///
        ///Here you can determine changes in signal strength based on how far you are from the antenna.
        ///
        ///You can do a transition analysis on the signals, moving away from the antenna and your computer for 4 or more seconds and then returning, moving the mouse or pressing a key.
        ///
        ///A graph of the signal strength will be shown from 4 seconds before you get to your computer to 4 seconds after.
        ///
        ///You can also just record the signals, moving further and nearer to the antenna, noticing  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserAnalysis {
            get {
                return ResourceManager.GetString("UserAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move away from the detector&apos;s antenna and computer for more than 4 seconds
        ///and return, then move the mouse or press a key to indicate that you&apos;re near..
        /// </summary>
        internal static string UserTransitionAnalysis {
            get {
                return ResourceManager.GetString("UserTransitionAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the RTL SDR spectrum analyzer for detecting frequencies that you&apos;re emitting or reradiating.
        ///
        ///The QuickStart form will now be shown. On activating it the automated detection process will start.
        ///
        ///Signal data will be processed for when you&apos;re near to the antenna and further away. Stronger signals
        ///when near indicate that you&apos;re emitting or reradiating a signal.
        ///
        ///The antenna should be placed near your computer, on your desk and extended.
        ///
        ///Preferably a yagi should be used. It can be placed a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
